version: '3'
services:
  devphp:
    build: .
    container_name: devphp
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./approot:/var/www/html"
  devmysql:
    image: mysql:latest
    container_name: devmysql
    volumes:
      - mysqldb-volume:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'testdb'
      MYSQL_USER: 'testuser'
      MYSQL_PASSWORD: 'testpw'
      MYSQL_ROOT_PASSWORD: 'root'
    restart: always
  migration:
    build: './migrations'
    container_name: devmigration
    volumes:
      - ./migrations/script:/docker-entrypoint-migrations.d
    links:
      - devmysql
    environment:
      MYSQL_HOST: 'devmysql'
      MYSQL_DATABASE: 'testdb'
      MYSQL_USER: 'testuser'
      MYSQL_PASSWORD: 'testpw'

volumes:
  mysqldb-volume:
